providers:
  - name: registry.terraform.io/hashicorp/aws
  - name: registry.terraform.io/carlpett/sops
  - name: registry.terraform.io/integrations/github
  - name: registry.terraform.io/hashicorp/tls
