#!/bin/bash
set -euC

if [[ -f "Brewfile" ]] && [[ "$(uname -s)" = "Darwin" ]]; then
  brew bundle check >/dev/null 2>&1  || {
    echo "==> Installing Homebrew dependencies…"
    brew bundle
  }
fi

if [[ -f "aqua.yaml" ]]; then
    aqua i
fi
