---
name: pr-agent

on:
  pull_request:
    types: [opened, reopened, synchronize]
  issue_comment:
    types: [created, edited]
  issues:
    types: [labeled]

permissions: {}

jobs:
  pr_agent:
    runs-on: ubuntu-latest
    name: Run PR Agent
    if: ${{ github.event.sender.type != 'Bot' }}
    permissions:
      pull-requests: write # To write PR comment
      issues: write
    steps:
      - id: labels
        shell: bash
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.number }}
        run: |
          json=$(gh pr view "$PR_NUMBER" --json labels | jq -c '.labels|map(.name)')
          echo "json=$json" >> "$GITHUB_OUTPUT"

      - id: pr-agent
        if: ${{ contains(fromJSON(steps.labels.outputs.json), 'review-required') }}
        uses: Codium-ai/pr-agent@8218fa6e131feabbf26c58677dd8fe2d9c1f1138 # v0.26
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_REVIEWER.EXTRA_INSTRUCTIONS: 'Please use Japanese in descriptions.'
          PR_DESCRIPTION.EXTRA_INSTRUCTIONS: 'Please use Japanese in descriptions. Titles should have prefix of commitlint pattern such as `feat:`, `chore:`, `test:`, `fix:`, `ci:`, `docs:` etc'
          CONFIG.MODEL: gpt-3.5-turbo
