---
name: release

on:
  push:
    tags:
      - "v*"
permissions: {}
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # required to create a release
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0

      - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version-file: go.mod
          cache: true

      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@7bfa3a4717ef143a604ee0a99d859b8886a96d00 # v1.9.3
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: "homebrew-ecsexec"

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@7ec5c2b0c6cdda6e8bbb49444bc797dd33d74dd8 # v5.0.0
        with:
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ steps.GITHUB_TOKEN }}
          TAP_GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
