name: Detect drift
on:
  workflow_dispatch:
    inputs: {}
  schedule:
    # daily
    - cron: '0 0 * * *'
jobs:
  pick-out-drift-issues:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      issues: ${{steps.pick-out-drift-issues.outputs.issues}}
      has_issues: ${{steps.pick-out-drift-issues.outputs.has_issues}}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: aquaproj/aqua-installer@f13c5d2f0357708d85477aabe50fd3f725528745 # v3.1.0
        with:
          aqua_version: v2.29.0
        env:
          AQUA_GITHUB_TOKEN: ${{github.token}}

      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        with:
          app_id: ${{secrets.TFACTION_APP_ID}}
          private_key: ${{secrets.TFACTION_APP_PRIVATE_KEY}}
          # issues:read - List issues
          permissions: >-
            {
              "issues": "read"
            }
          # repository where Drift Detection issues are hosted
          repositories: >-
            ["${{github.event.repository.name}}"]

      - run: tfaction pick-out-drift-issues
        id: pick-out-drift-issues
        env:
          GITHUB_TOKEN: ${{steps.generate_token.outputs.token}}

  detect-drift:
    name: "detect-drift (${{matrix.issue.target}})"
    runs-on: ${{matrix.issue.runs_on}}
    needs: pick-out-drift-issues
    permissions:
      issues: write # For github-comment and tfcmt
      contents: write # To push commits
      id-token: write # For OIDC
    if: fromJSON(needs.pick-out-drift-issues.outputs.has_issues)
    strategy:
      fail-fast: false
      matrix:
        issue: ${{fromJSON(needs.pick-out-drift-issues.outputs.issues)}}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        with:
          app_id: ${{secrets.TFACTION_APP_ID}}
          private_key: ${{secrets.TFACTION_APP_PRIVATE_KEY}}
          # issues:write - Create and update issues
          permissions: >-
            {
              "issues": "write"
            }
          # issues of Drift Detection
          repositories: >-
            ["${{github.event.repository.name}}"]

      - uses: aquaproj/aqua-installer@f13c5d2f0357708d85477aabe50fd3f725528745 # v3.1.0
        with:
          aqua_version: v2.29.0
        env:
          GITHUB_TOKEN: ${{github.token}}

      - uses: suzuki-shunsuke/tfaction/set-drift-env@98cdb1548f3638f49ed35a88dac04b46ad65478e # v1.15.2
        with:
          issue: ${{toJSON(matrix.issue)}}

      - uses: suzuki-shunsuke/tfaction/export-secrets@98cdb1548f3638f49ed35a88dac04b46ad65478e # v1.15.2
        with:
          secrets: ${{ toJSON(secrets) }}

      - uses: suzuki-shunsuke/tfaction/setup@98cdb1548f3638f49ed35a88dac04b46ad65478e # v1.15.2
        with:
          github_token: ${{steps.generate_token.outputs.token}}
        env:
          GITHUB_TOKEN: ${{steps.generate_token.outputs.token}}

      - uses: suzuki-shunsuke/tfaction/test@98cdb1548f3638f49ed35a88dac04b46ad65478e # v1.15.2
        with:
          github_token: ${{steps.generate_token.outputs.token}}
        env:
          GITHUB_TOKEN: ${{steps.generate_token.outputs.token}}

      - uses: suzuki-shunsuke/tfaction/terraform-plan@98cdb1548f3638f49ed35a88dac04b46ad65478e # v1.15.2
        with:
          github_token: ${{steps.generate_token.outputs.token}}
        env:
          GITHUB_TOKEN: ${{steps.generate_token.outputs.token}}

      - uses: suzuki-shunsuke/tfaction/update-drift-issue@98cdb1548f3638f49ed35a88dac04b46ad65478e # v1.15.2
        if: always()
        with:
          status: ${{job.status}}
          github_token: ${{steps.generate_token.outputs.token}}
