name: Synchronize drift issue description

on:
  issue_comment:
    types:
      - created

jobs:
  sync-issue:
    runs-on: ubuntu-latest
    if: |
      !github.event.issue.pull_request && startsWith(github.event.issue.title, 'Terraform Drift (') && endsWith(github.event.issue.title, ')') && github.actor == 'Taiki130'
    permissions:
      issues: write
    steps:
      - uses: suzuki-shunsuke/tfaction/sync-drift-issue-description@83e231ae2a2d2da48105f2ef9d6095964f70cd29 # v1.12.0
