name: Synchronize drift issue description

on:
  issue_comment:
    types:
      - created

jobs:
  sync-issue:
    runs-on: ubuntu-latest
    if: |
      !github.event.issue.pull_request && startsWith(github.event.issue.title, 'Terraform Drift (') && endsWith(github.event.issue.title, ')') && github.actor == 'Taiki130'
    permissions:
      issues: write
    steps:
      - uses: suzuki-shunsuke/tfaction/sync-drift-issue-description@f56d1ae7fd22841f64c1c092148bc55bcb1f24d4 # v1.13.4
