---
name: Trivy
on:
  pull_request:
    paths:
      - "tofu/*.tf"
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
permissions: {}
jobs:
  trivy:
    permissions: {}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@b2933f565dbc598b29947660e66259e3c7bc8561 # 0.20.0
        with:
          scan-type: 'config'
          scan-ref: ./tofu/
          exit-code: '1'
