---
name: Trivy
on:
  pull_request:
    paths:
      - "tofu/*.tf"
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
jobs:
  trivy:
    permissions: {}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@d710430a6722f083d3b36b8339ff66b32f22ee55 # 0.19.0
        with:
          scan-type: 'config'
          scan-ref: ./tofu/
          exit-code: '1'
