---
name: Trivy
on:
  pull_request:
    paths:
      - "tofu/*.tf"
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
permissions: {}
jobs:
  trivy:
    permissions: {}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@d710430a6722f083d3b36b8339ff66b32f22ee55 # 0.19.0
        with:
          scan-type: 'config'
          scan-ref: ./tofu/
          exit-code: '1'
